CREATE TABLE icp_entities (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    icp_code VARCHAR(50) NOT NULL UNIQUE COMMENT 'ICP备案/许可证号',
    approval_date DATE COMMENT '审核通过日期',
    entity_name VARCHAR(255) NOT NULL COMMENT '主办单位名称',
    entity_type VARCHAR(50) NOT NULL COMMENT '主办单位性质',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);