CREATE TABLE icp_services (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    entity_id BIGINT UNSIGNED NOT NULL COMMENT '关联的主体ID',
    service_code VARCHAR(50) NOT NULL COMMENT '服务备案号',
    website_id BIGINT UNSIGNED NOT NULL COMMENT '关联的网站ID',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (entity_id) REFERENCES icp_entities(id),
    FOREIGN KEY (website_id) REFERENCES websites(id)
);