CREATE TABLE websites (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    domain VARCHAR(255) NOT NULL COMMENT '域名',
    subdomain VARCHAR(255) COMMENT '子域名',
    full_url TEXT NOT NULL COMMENT '完整URL',
    port INT COMMENT '端口',
    title VARCHAR(255) COMMENT '网站标题',
    ip VARCHAR(45) COMMENT '服务器IP',
    is_malicious BOOLEAN DEFAULT FALSE COMMENT '是否是恶意站点',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);